server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Внешняя директория с конфигурациями сервисов (в реальном проекте — git-репозиторий)
          search-locations: file:./config-repo

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
